server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uploaddoc
    username: root
    password: asura

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true